name: CI/CD for Attendance Management System

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./frontend  
      run: |
        npm install


  build-and-publish:
    needs: build-and-test  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./front-end  
        file: ./frontend/Dockerfile  
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/attendance-system-frontend:latest

    - name: Image Digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}
